apiVersion: v1
kind: Service
metadata:
  name:  pavan-twittertrend-service
  namespace: imran
spec:
  type: NodePort
  selector:
    app: imran-twittertrend
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000